services:
  backend:
    build: ./app/backend
    container_name: reminder-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=appdb
      - PGPORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: reminder-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
