pipeline { 
  agent any

  environment {
    IMAGE_TAG = "yourdockeruser/reminder-app:${env.BUILD_NUMBER}"
    BACKEND_DIR = "app/backend"
    FRONTEND_DIR = "app/frontend"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Janzz143/reminder-app-infra']])
      }
    }

    stage('Test Backend') {
      steps {
        dir(BACKEND_DIR) {
          sh 'npm install'
          sh 'npm test'
        }
      }
    }

    stage('Security Scan') {
      steps {
        dir(BACKEND_DIR) {
          // Node.js dependency audit
          sh 'npm audit --audit-level=high || true'
        }
      }
    }

    stage('Build and Push Docker Images') {
      when {
        branch 'main'
      }
      steps {
        script {
          // Build and push backend and frontend Docker images
          docker.build("${IMAGE_TAG}-backend", "./${BACKEND_DIR}").push()
          docker.build("${IMAGE_TAG}-frontend", "./${FRONTEND_DIR}").push()
        }
      }
    }

    stage('Scan Docker Images') {
      when {
        branch 'main'
      }
      steps {
        // Trivy vulnerability scan for built images
        sh "trivy image --severity HIGH,CRITICAL ${IMAGE_TAG}-backend || true"
        sh "trivy image --severity HIGH,CRITICAL ${IMAGE_TAG}-frontend || true"
      }
    }

    stage('Deploy to Staging') {
      steps {
        sh 'chmod +x scripts/deploy.sh
            git add scripts/deploy.sh
            git commit -m "Make deploy.sh executable"
            git push
            ./scripts/deploy.sh'
      }
    }

    stage('Manual Approval for Prod') {
      steps {
        input message: "Deploy to Production?", ok: "Deploy"
      }
    }

    stage('Deploy to Production') {
      steps {
        sh './scripts/deploy-prod.sh'
      }
    }
  }

  post {
    failure {
      echo "Build failed"
      // Add Slack or email notifications here
    }
    success {
      echo "Build succeeded"
      // Add Slack or email notifications here
    }
  }
}

